[providers]
node = "18"

[phases.setup]
nixPkgs = ["nodejs-18_x"]

[phases.install]
cmd = "npm install"

[phases.build]
cmd = "npm run build"

[start]
cmd = "npm start"

[variables]
NODE_ENV = "production"
PORT = "3001"