[build]
cmd = "cd backend && npm install"

[start]
cmd = "cd backend && npm start"

[variables]
NODE_ENV = "production"
PORT = "3001"

[phases.setup]
nixPkgs = ["nodejs-18_x", "npm-9_x"]

[phases.install]
cmd = "cd backend && npm ci --only=production"

[phases.build]
cmd = "cd backend && npm run build"